package ajfmo.inventario.entities;
// Generated 08/02/2018 05:04:40 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.AccessType;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Deposito generated by hbm2java
 */
@Entity
@Table(name = "deposito", catalog = "inventario", uniqueConstraints = @UniqueConstraint(columnNames = "descripcion_deposito"))
public class Deposito implements java.io.Serializable {

	private static final long serialVersionUID = -5135393562420088474L;

	private IntegerProperty idDeposito;
	private int _idDeposito;
	private StringProperty descripcionDeposito;
	private String _descripcionDeposito;

	public Deposito() {
	}

	public Deposito(String descripcionDeposito) {
		this.descripcionDeposito = new SimpleStringProperty(descripcionDeposito);
	}

	/*******************/
	/**				  **/
	/*** Source Code ***/
	/**				  **/
	/*******************/

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDeposito", unique = true, nullable = false)
	// Metodos atributo: idDeposito
	public Integer getIdDeposito() {
		if (idDeposito == null) {
			return _idDeposito;
		} else {
			return idDeposito.get();
		}
	}

	public void setIdDeposito(Integer idDeposito) {
		if (this.idDeposito == null) {
			_idDeposito = idDeposito;
		} else {
			this.idDeposito.set(idDeposito);
		}
	}

	public IntegerProperty IdDepositoProperty() {
		if (idDeposito == null) {
			idDeposito = new SimpleIntegerProperty(this, "idDeposito", _idDeposito);
		}
		return idDeposito;
	}

	@Column(name = "descripcion_deposito", unique = true, nullable = false, length = 45)
	// Metodos atributo: descripcionDeposito
	public String getDescripcionDeposito() {
		if (descripcionDeposito == null) {
			return _descripcionDeposito;
		} else {
			return descripcionDeposito.get();
		}
	}

	public void setDescripcionDeposito(String descripcionDeposito) {
		if (this.descripcionDeposito == null) {
			_descripcionDeposito = descripcionDeposito;
		} else {
			this.descripcionDeposito.set(descripcionDeposito);
		}
	}

	public StringProperty DescripcionDepositoProperty() {
		if (descripcionDeposito == null) {
			descripcionDeposito = new SimpleStringProperty(this, "descripcionDeposito", _descripcionDeposito);
		}
		return descripcionDeposito;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deposito")
	private Set<Productos> productoses = new HashSet<Productos>(0);

	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

}
